### ISSUE TITLE
Loots do not work properly on servers, but locally they work

### ISSUE THREAD

**Issue by elchimuelogamer** [Lythom/capsule#6] opened 2018-03-24 07:20 UTC
177/5000
Configure the loots of the capsules that appear in chests and play on a mods server, use them there is nothing, on the other hand when I play in a single player (local) if they appear

Version where the problem is presented

minecraft in 1.12.2
forge 1.12.2-14.23.2.2624
Capsule-1.12.2-3.1.63 (I think also Capsule-1.12.2-3.1.57)

I packed many other mods, but I will try to use the mod on a clean server without other mods, that is, only using capsule mod

This tells me the console of my server [capsule.items.CapsuleItem]: Capsule size must be an odd number to achieve consistency on deployment. Resized to: -1

**Comment by elchimuelogamer** [comment] 2018-03-24 08:25
I have tried to use mod capsule without using other modifications and the loots do not work either, I repeat they only work in a single player (local)

**Comment by Lythom** [comment] 2018-03-25 20:11
Thank you for your feedback !

I'll copy here your message from the capsule mod page as well for reference :    
> Excuse me. I have modified the loots of the following config / capsule / loots directory with custom structures and when I try it in a local world they work but when I load it to a server they do not work correctly, in the console I get this message when I use a capsule of the that are generated in chests
> This tells me the console of my server [capsule.items.CapsuleItem]: Capsule size must be an odd number to achieve consistency on deployment. Resized to: -1
> I checked the structures to see if it was odd but most are odd and even then it is not fixed
> so when I try to use any of the capsules that have these structures, they appear to me as having a size of 1x1x1 probe creating a new server with only capsule mod and it does not work either

I can reproduce the problem using a fresh dedicated server with capsule release build but not using a development build. This means It will take me some time to debug this out, but I should have all data I need to fix it.

I look into this this issue week and let you now as soon as I have some progress.

**Comment by Lythom** [comment] 2018-03-26 12:21
After some digging : the problem is present only on linux environment, and when there are uppercase characters in the file name (which is the case of all default templates).

As a quick workaround, renaming all you template files using only lowercase characters will solve the problem. You'll then have to either restart the server or use the command `/capsule reloadLootList`.

I'll work on a fix to allow uppercase characters as well in futur versions.

**Comment by Lythom** [comment] 2018-03-26 14:10
After more investigating, lowercase naming is a requirement for minecraft assets since 1.11. So I'll update the documentation and use lowercase only for the default templates as well.

Starting next version of capsule, the capsule items created from templates will have their names capitalized. Ex: "small villager house.nbt" Will give a "Small Villager House" capsule.

Next version of capsule will be available shortly on the mod page https://minecraft.curseforge.com/projects/capsule.

Thanks again for reporting this issue, 
Have Fun !

**Comment by Lythom** [comment] 2019-05-18 08:37
Fixed by 627c92b6233886fbcd3716e7b6a9128abd6e55ab. To be released in coming days.

**Closed by Lythom** 2019-05-18 08:37 UTC
Labels: bug

**Comment by Lythom** [comment] 2019-05-28 14:04
New version of capsule released : https://minecraft.curseforge.com/projects/capsule/files/2716860
